[package]
name = "parallel-hash-poc"
authors = ["Sivaram Dhakshinamoorthy <siv2ram@gmail.com>"]
version = "0.1.0"
edition = "2021"
description = "A specification for half-aggregation"

[lib]
path = "src/parallel_hash.rs"

[dependencies]
hex = "0.4.3"
digest = "0.10.7"
sha3 = "0.10.8"